# Generated by Django 4.1.1 on 2022-10-11 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("IllustNet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IllustPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("illust_url", models.CharField(max_length=300)),
                ("views", models.IntegerField(null=True)),
                ("upload_time", models.DateTimeField(verbose_name="생성일")),
                ("brief_comment", models.CharField(max_length=300)),
                (
                    "illustrator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="illustrator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommend",
                    models.ManyToManyField(
                        related_name="recommend_user", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=300)),
                ("upload_time", models.DateTimeField(verbose_name="생성일")),
                (
                    "illustrator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
