# Generated by Django 4.1.1 on 2022-10-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IllustNet", "0002_illustpost_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illustpost",
            name="brief_comment",
            field=models.TextField(),
        ),
    ]
