# Generated by Django 4.1.1 on 2022-10-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IllustNet", "0003_alter_illustpost_brief_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illustpost",
            name="illust_url",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
