# Generated by Django 4.1.1 on 2022-10-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IllustNet", "0004_alter_illustpost_illust_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illustpost",
            name="brief_comment",
            field=models.TextField(verbose_name="일러스트에 대한 설명"),
        ),
        migrations.AlterField(
            model_name="illustpost",
            name="illust_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name=""
            ),
        ),
    ]
