# Generated by Django 4.1.1 on 2022-10-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IllustNet', '0006_illustpost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustpost',
            name='views',
        ),
        migrations.AlterField(
            model_name='illustpost',
            name='title',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='제목'),
        ),
    ]
