# Generated by Django 4.1.1 on 2022-10-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("IllustNet", "0007_remove_illustpost_views_alter_illustpost_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="illustrator",
            new_name="comment_writer",
        ),
        migrations.AddField(
            model_name="comment",
            name="illust",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="IllustNet.illustpost",
            ),
        ),
    ]
