# Generated by Django 4.1.1 on 2022-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IllustNet", "0008_rename_illustrator_comment_comment_writer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illustnetuser",
            name="banner_img_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="banner_img/", verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="illustnetuser",
            name="profile_img_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_img/", verbose_name=""
            ),
        ),
    ]
